###########################
### Fraudulent or not   ###
### Sari Vesiluoma 2019 ###
###########################

# Ensuring having required libraries
if(!require(tidyverse)) install.packages("tidyverse", repos = "http://cran.us.r-project.org")
library(tidyverse)
if(!require(caret)) install.packages("caret", repos = "http://cran.us.r-project.org")
library(caret)
if(!require(readr)) install.packages("readr", repos = "http://cran.us.r-project.org")
library(readr)

# Synthetic Financial Datasets For Fraud Detection
# Synthetic datasets generated by the PaySim mobile money simulator
# https://www.kaggle.com/ntnu-testimon/paysim1
# https://www.kaggle.com/ntnu-testimon/paysim1/download#PS_20174392719_1491204439457_log.csv
# I have downloaded the file using the above links and unzipped it to my local git directory
# Read the dataset to this scripti

fraud_or_not <- read_csv("PS_20174392719_1491204439457_log.csv")
summary(fraud_or_not)
str(fraud_or_not)
class(fraud_or_not)
